[package]
name = "native-ts-mir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "*"
paste = "1.0"

llvm-sys = "160"
itoa = "1"